name: flutter_bubble_chart_plus
description: A fork that implements custom colors, option to hide values and text-wrapping of a beautiful and interactive bubble chart widget for Flutter with physics-based animations. Perfect for visualizing market data, statistics, and dynamic datasets.
version: 1.0.7
homepage: https://github.com/Sheikh-Rashdan/flutter_bubble_chart_plus
repository: https://github.com/Sheikh-Rashdan/flutter_bubble_chart_plus
issue_tracker: https://github.com/Sheikh-Rashdan/flutter_bubble_chart_plus/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
